### ISSUE TITLE
请问一下如何动态添加自定义图片

### ISSUE THREAD

**Issue by ray-zyh** [openwise-cn/react-native-amap3d-openwise#1]
<MapView
         style={{flex: 1,position:'relative'}}
 >      
        <MapView.Marker
          image="flag"
          title="自定义图片"
          coordinate={this._coordinates}
        />
        <View>
          { this.List.map((item, index) => { return ( <MapView.Marker            
            key={index}
            title={String(item.latitude)}
            onPress={() => {this._clickItem(item)}}
            icon={() => <View>
              <Image
                style={styles.customIcon}
                source={this.Img} />
              </View>}
             coordinate={item}
           />)})}
           </View>
         </MapView>

从后台获取来坐标后 赋值给 this.List  ,但是地图并不渲染出来图片,是这个地图组件本身不支持还是我的代码需要哪里改进,请赐教!

**Comment by lzy3366** [comment]
我是通过数组实现的动态渲染，并且正常执行。
<MapView>
            {pointMarkers.length > 0 ? pointMarkers : null}
            {enableSetSource ? carMarkers : null}
            <Marker 
              key={ 'OrderCar' } 
              color="green" 
              coordinate={{ latitude: carLatitude, longitude: carLongitude, }}
              image="ic_car"
            />
</MapView>
这里面pointMarkers和carMarkers都是动态点的数组

**Comment by lzy3366** [comment]
数组中增加动态点的案例给你一个
addStartMarker (state, { payload }) {
      let { latitude, longitude } = payload
      if (!latitude) {
        latitude = 0
      }
      if (!longitude) {
        longitude = 0
      }
      const startMarkers = [
        <Marker 
          key={ 'StartPoint' } 
          color="green" 
          style={{zIndex: -1}}
          coordinate={{ latitude: latitude, longitude: longitude, }}
          icon={() => (
            <View>
              <Image style={{width:48,height:48,}}
                source={require('../assets/images/ic_startingPoint.png')}
                // source={{ uri: 'app_assets_images_ic_startingPoint' }}
              />
            </View>
          )}
        />,
        ...state.pointMarkers]
      return Object.assign({}, state, {
        pointMarkers: startMarkers
      })
    }
